controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# auth login route
api_login_check:
    path: /api/login

# api doc route
when@dev:
    app.swagger_ui:
        path: /api/doc
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
