parameters:

services:
    _defaults:
        autowire: true      # automatically injects dependencies in your services.
        autoconfigure: true # automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # error event subscriber
    App\Event\Subscriber\ErrorEventSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # handles success login event
    App\Event\Subscriber\LoginEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    # validate jwt tokens middleware
    App\Middleware\AuthTokenValidateMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 5 }

    # security check middleware
    App\Middleware\SecurityCheckMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 4 }

    # maintenance mode checker
    App\Middleware\MaintenanceMiddleware:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 3 }

    # database online checker
    App\Middleware\DatabaseOnlineMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 2 }

    # escape request data
    App\Middleware\EscapeRequestDataMiddleware:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 1 }
