# This Docker Compose configuration defines local development services.
version: '3'

# docker network config
networks:
    dev:
        driver: bridge

services:
    # database container
    mysql:
        image: mysql:latest
        container_name: engal_mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./docker/configs/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
            - ./docker/services/mysql_database:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - dev

    # api server container
    backend:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: engal_backend
        restart: always
        depends_on:
            - mysql
        environment:
            - DATABASE_DRIVER=pdo_mysql
            - DATABASE_HOST=mysql
            - DATABASE_PORT=3306
        volumes:
            - ./docker/configs/apache-api.conf:/etc/apache2/sites-available/000-default.conf
            - ./docker/configs/php.ini:/usr/local/etc/php/php.ini:ro
            - ./:/var/www
        ports:
            - "1337:80"
        networks:
            - dev

    # frontend container
    frontend:
        image: node:latest
        container_name: engal_frontend
        restart: always
        volumes:
            - ./frontend:/app
        ports:
            - "80:3000"
        networks:
            - dev 
        depends_on:
            - mysql
            - backend
        working_dir: /app 
        command: npm start
