framework:
    messenger:
        # transports process settings get from config
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        # messages list
        routing:
            'App\Message\PreloadThumbnailsMessage': async
