nelmio_api_doc:   
    # doc title
    documentation:
        info:
            title: 'Engal API'
            description: Engal REST-API documentation
            version: '%env(APP_VERSION)%'

        # static docs
        paths:
            # JWT Security endpoint
            /api/login_check:
                post:
                    summary: User Login
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: Successful login
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Invalid credentials
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                    tags: ['Auth']
