security:
    # password hasher
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'argon2i'
            memory_cost: 4096
            cost: 10

    # user entity providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # app firewalls
    firewalls:
        content:
            pattern: ^/api/media/content
            stateless: true
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                username_path: username
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    # app access manager 
    access_control:
        # exclude media content from main firewall
        - { path: ^/api/media/content,      roles: PUBLIC_ACCESS }

        # public access routes
        - { path: ^/api/register,      roles: PUBLIC_ACCESS }
        - { path: ^/api/login,         roles: PUBLIC_ACCESS }
        - { path: ^/api/doc,           roles: PUBLIC_ACCESS }

        # user access routes
        - { path: ^/api,               roles: ROLE_USER }
