security:
    # password hasher
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # user entity providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # app firewalls
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                username_path: username
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    # app access manager 
    access_control:
        - { path: ^/api/register,      roles: PUBLIC_ACCESS }
        - { path: ^/api/login,         roles: PUBLIC_ACCESS }
        - { path: ^/api/doc,           roles: PUBLIC_ACCESS }
        - { path: ^/api,               roles: ROLE_USER }
